### ISSUE TITLE
We need a cart / basket model

### ISSUE THREAD

**Issue by CelineChole** [mercury-cap/graceshopper#8]

**Comment by CelineChole** [comment]
We need a cart/basket model to keep track of incomplete orders. 

If the user is logged in, we ignore session id, if the user is not logged in we use session id to keep track of them. 

Model: 
- product ids (list of all the products)
- user id
- session id

a user can only have one cart
a session can only have one cart

**Comment by bneptune** [comment]
Is this different than the orders model? ...assuming that an order is generated once a user puts something in their cart and status is 'pending' for incomplete orders until they check out.

**Comment by CelineChole** [comment]
Yes, because the user might not complete the order and we will be able to easily and safely delete the data into this table. With the cart we won't be checking if the product is available.

An order should be immutable after being created and without any risk to get problems about price 
 and quantity and we should be checking if the product is available in our stock - we wouldn't do this check everytime we load the cart. 

I think we are missing some important information on the order model such as the price and the payment method.
